Generating the user consent URI no longer fails on Python 3.
